### ISSUE TITLE
CSS file can not be imported (missing token in form)

### ISSUE THREAD

**Issue by NicoDucou** [chamilo/chamilo-lms#3975]
On the page main/admin/settings.php?category=Stylesheets#tabs-3 when validating the form it always shows the message that the token is not validated and the CSS file is never imported.

Since the commit https://github.com/chamilo/chamilo-lms/commit/bf50545e848805c9f123e6736eeba2edd7327bbc#diff-3b92311ca8f4223f9e4bd967854e03eba80d6707b77130b9b26706949c92a5b7R1431 when ever a form is validated it should check that the security token is valid. The problem is that in this form for stylesheet upload the token is never validated.

It calls Security::check_token('form', $this);
And in this function I don't know why the form token and the sessionToken are always different so the action is always blocked and the Stylesheet is not imported. 

Tested on Chamilo 1.11.x of 2021/09/21

**Comment by christianbeeznest** [comment]
Hola @NicoDucou puedes confirmar si esta bien ahora porfavor ? Esto es mi PR con el fix https://github.com/chamilo/chamilo-lms/pull/3979/commits/0f3b54fa16f6ba9ba030d99a18102e4f79e8b07e

Gracias.

**Comment by ywarnier** [comment]
@NicoDucou this one is fixed, right?

**Comment by xam1234** [comment]
@ywarnier When do you plan to release version 1.11.18 ?

**Comment by NicoDucou** [comment]
> @NicoDucou this one is fixed, right?

Yes

**Comment by ywarnier** [comment]
> @ywarnier When do you plan to release version 1.11.18 ?

When it's ready (soon)

**Comment by Chabi01** [comment]
Hi,
I'm using the V1.11.16 (softaculous), the error is still here...

**Comment by Chabi01** [comment]
I get exactly on submit : 
Not Found

The requested URL was not found on this server.
Additionally, a 404 Not Found error was encountered while trying to use an ErrorDocument to handle the request.
The url triggered is : /main/admin/admin/settings.php?category=Stylesheets#tabs-3

No error message even on test server mode.

**Comment by Chabi01** [comment]
2 times "admin" ??

**Comment by Chabi01** [comment]
For the record, I have solve this by modifying the file mai/admin/settings.lib.php, line 400
from
api_get_path().'admin/settings.php?category=Stylesheets#tabs-3'
to
api_get_path().'settings.php?category=Stylesheets#tabs-3'
