### ISSUE TITLE
[C2] mail_notify_* extra fields have broken "possible values" after install

### ISSUE THREAD

**Issue by ywarnier** [chamilo/chamilo-lms#6138]
![Image](https://github.com/user-attachments/assets/c7c9368a-4713-4747-a284-94b900ad6003)

**Comment by christianbeeznest** [comment]
It is fixed in this PR https://github.com/chamilo/chamilo-lms/pull/6140 

Thanks for confirmation.

**Comment by ywarnier** [comment]
This is better. However, still for the same mail_notify_invitation field, for example, when I click [Edit extra field options](https://testing26.beeznest.com/main/admin/extra_field_options.php?type=user&field_id=13), I can see that the "Value" column is empty. When I edit the second option ("At once"), the "Value" input is empty and is... not an input.

I think the form itself is correct (you shouldn't be able to change the value of an option afterwards, just how it appears), but there must be something wrong at installation that adds the option "At once" but leaves its value empty.

**Comment by ywarnier** [comment]
Sorry, I just saw that the DataFixtures include setting a value. Will test again.

**Comment by ywarnier** [comment]
Yes, sorry. This works. There's still an issue with the registration form showing the title of those fields and no option, but this can go into a distinct issue.
