### ISSUE TITLE
[C2] Delete unused documents when course deleted

### ISSUE THREAD

**Issue by NicoDucou** [chamilo/chamilo-lms#6372]
In Chamilo 2 when deleting a course it deletes all the registries in the database.
But the files in var/upload/resource are still present.
It is good because resource could be used in many different courses.
So when deleting a course we should check if the resource_file that was used in a course do not have anymore resource_link associated to it then the resource_file registry should be deleted and the file on the disc as well to avoid living unused resources and files.

**Comment by ywarnier** [comment]
When deleting a course:
- add an option/popup to ask "When deleting this course, the documents available *only* in this course (if any) will remain available on the platform through the 'File information' tool, available only to the platform administrator. Would you like to delete those documents definitively instead?"
- add an option to the "File information" page to attach an orphan document (one that has no resource_link) to a course (in this case it goes to the root of the documents tool of the course, in hidden mode)
- add an option to the "File information" page to delete an orphan document definitively.

**Comment by christianbeeznest** [comment]
It is checked and improved with this PR https://github.com/chamilo/chamilo-lms/pull/7068

Thanks for confirmation.

**Comment by NicoDucou** [comment]
Hi @christianbeeznest 
It works but it would be better to have a course selector instead of writing a course code to avoid typing error and people that do not know the code of the course they want to use.

Also as discussed yesterday it would be good to be able to attach a file to a course even if it is not orphan, So we could have a document used in many different courses and on the File Information window we would have on the "Course" line a list of courses and a + at the end to add a course where this document is available.

I accepted the PR because it works how it is now, so you can just complete with those 2 indications.

**Comment by christianbeeznest** [comment]
> Hi [@christianbeeznest](https://github.com/christianbeeznest) It works but it would be better to have a course selector instead of writing a course code to avoid typing error and people that do not know the code of the course they want to use.
> 
> Also as discussed yesterday it would be good to be able to attach a file to a course even if it is not orphan, So we could have a document used in many different courses and on the File Information window we would have on the "Course" line a list of courses and a + at the end to add a course where this document is available.
> 
> I accepted the PR because it works how it is now, so you can just complete with those 2 indications.

It is checked and improved with this PR https://github.com/chamilo/chamilo-lms/pull/7094

Thanks for confirmation.

**Comment by NicoDucou** [comment]
Hi @christianbeeznest 
Your PR is all good, but I could not merged it because of conflicts.
I let you check the conflict and merge the PR to complete this task
Good work

**Comment by christianbeeznest** [comment]
> Hi [@christianbeeznest](https://github.com/christianbeeznest) Your PR is all good, but I could not merged it because of conflicts. I let you check the conflict and merge the PR to complete this task Good work

It is fixed the conclict and merged with master now.

Thanks

**Comment by christianbeeznest** [comment]
Implemented a course selector with search, and the attach action now works for any ResourceFile (not only orphans).
When attaching, we reuse the same ResourceNode and just add extra ResourceLinks, so a single file can be used by multiple courses and the “Course(s)” line shows all of them with a “+” button to add more.

Note: when the “also create a visible document” option is used, the Documents tool creates its own ResourceFile/ResourceNode/ResourceLink per course, which explains the additional rows with Links = 1.

**Comment by NicoDucou** [comment]
Hi @christianbeeznest 

I think we did not understand the same thing.
The idea is to have by default only a resource_link with the new course attach to the file but no create a new ResourceFile/ResourceNode

From what I tested on testing24 when attaching 3 courses to a file it create for every course a new ResourceFile/ResourceNode/ResourceLink when it shoud be only a new ResourceLink that points to the same ResourceNode.

**Comment by ywarnier** [comment]
So... We just observed that there is one remaining structural issue in C2 Beta 1, which is that sharing documents between courses is possible, but it is not possible to then modify the position of the document inside the documents hierarchy in the new course (it would have to be fixed at the root or something like that).

After much brainstorming, we realized that we are further than we thought in the implementation of the notion of resources, and that the c_document table has now become sort of an extra field (or "meta") table for resource_node in terms of document information. Indeed, we have almost everything we need in the combination of resource_node + resource_file + resource_link.
Only the "readonly" and "template" status are missing from those tables, as c_document only offers the title, comment, filetype, readonly and template fields, and resource_node.title exists (and resource_file.title), resource_file.description exists (to replace comment), resource_file.mime_type exists (to replace filetype).

Also, c_document is bound on a one-to-one relationship with resource_node, so we *could not* have several c_document for one single resource_node.

However, we can have several resource_link for one resource_node (one for each *context*) and this is already helpful, but in the case of sharing a document, the problem is that resource_link has no information on relative position in a hierarchy (it has a display_order, but no parent).

 So the idea would be to just add a `resource_link.parent_id` that would allow us to store *where* the document is in the particular context of the new course where we are sharing it.

We can already share a document in a new course without the parent_id info. However, this would not show in the documents list of the new course *because* the documents tool mainly queries c_document to get the list. This, however, is not really necessary (as per the fact that c_document is only a meta-information table on top of resource_node/link/file).

So the idea is now to add this `resource_link.parent_id` *and* change the documents code so its main source is now `resource_link` (and not c_document anymore, as it is only "meta" in its use).

New to do (in charge of @christianbeeznest):
- [x] Add new migration to add resource_link.parent_id and update the entity accordingly
- [x] Pre-fill this parent_id field with the corresponding resource_node.parent_id (this value will always be the same in both tables *until* we start sharing documents and moving them around)
- [x] Update the documents tool code to base its documents list on resource_link where c_id = ... and s_id = ... resource_type_group = document
- [x] Look around to see if anything else might be affected (possibly the TinyMCE code for browsing files, the learning paths tool to browse documents and the backup/restore tool to select documents)

This will require a change to the database post-beta, which is contrary to our rules, but we believe it is worth cleaning this now to avoid hitting big walls later on in the 2.* family of versions.

**Comment by christianbeeznest** [comment]
> So... We just observed that there is one remaining structural issue in C2 Beta 1, which is that sharing documents between courses is possible, but it is not possible to then modify the position of the document inside the documents hierarchy in the new course (it would have to be fixed at the root or something like that).
> 
...
> This will require a change to the database post-beta, which is contrary to our rules, but we believe it is worth cleaning this now to avoid hitting big walls later on in the 2.* family of versions.

It is implemented a version about it with this PR https://github.com/chamilo/chamilo-lms/pull/7139

- We implemented resource_link.parent_id and refactored the documents tool to build the folder tree from resource_link instead of c_document, so shared documents can have their own position per course.

- We also adjusted the admin “files info” page to safely attach/detach files to courses and fixed document listing/preview in Documents and learning paths.

- Next step is to run additional tests on migrated portals (C1 → C2), especially for legacy/orphan files and existing learning paths, to ensure there are no regressions.

It requires testing and confirmation 

php bin/console doctrine:migrations:execute Chamilo\\CoreBundle\\Migrations\\Schema\\V200\\Version20251201164100
php bin/console doctrine:migrations:execute Chamilo\\CoreBundle\\Migrations\\Schema\\V200\\Version20251201173000

**Comment by NicoDucou** [comment]
Hi @christianbeeznest 

I tested your PR on testing23 and I have the followinf issues to be checked :

On testing23 the last migration before updating to your branch "GH-6372-4" was "Version20250725104800". So I had to apply all the migrations since then.

And I got the following errors :

```
root@testing:/var/www/testing23.beeznest.com/www# php bin/console doctrine:migrations:execute Chamilo\\CoreBundle\\Migrations\\Schema\\V200\\Version20250923205900

 WARNING! You are about to execute a migration in database "testing23" that could result in schema changes and data loss. Are you sure you wish to continue? (yes/no) [yes]:
 > 

[notice] Executing Chamilo\CoreBundle\Migrations\Schema\V200\Version20250923205900 up
[error] Migration Chamilo\CoreBundle\Migrations\Schema\V200\Version20250923205900 failed during Execution. Error: "An exception occurred while executing a query: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'parent_id' in 'INSERT INTO'"

In ExceptionConverter.php line 69:
                                                                                               
  An exception occurred while executing a query: SQLSTATE[42S22]: Column not found: 1054 Unkn  
  own column 'parent_id' in 'INSERT INTO'                                                      
                                                                                               

In Exception.php line 24:
                                                                                       
  SQLSTATE[42S22]: Column not found: 1054 Unknown column 'parent_id' in 'INSERT INTO'  
                                                                                       

In Statement.php line 130:
                                                                                       
  SQLSTATE[42S22]: Column not found: 1054 Unknown column 'parent_id' in 'INSERT INTO'  
                                                                                       

doctrine:migrations:execute [--write-sql [WRITE-SQL]] [--dry-run] [--up] [--down] [--query-time] [--configuration CONFIGURATION] [--em EM] [--conn CONN] [--] <versions>...


----------------------------------------------------------------------------------------------------------------------------------------------------------------------------


root@testing:/var/www/testing23.beeznest.com/www# php bin/console doctrine:migrations:execute Chamilo\\CoreBundle\\Migrations\\Schema\\V200\\Version20250928100200

 WARNING! You are about to execute a migration in database "testing23" that could result in schema changes and data loss. Are you sure you wish to continue? (yes/no) [yes]:
 > 

[notice] Executing Chamilo\CoreBundle\Migrations\Schema\V200\Version20250928100200 up
[error] Migration Chamilo\CoreBundle\Migrations\Schema\V200\Version20250928100200 failed during Execution. Error: "An exception occurred while executing a query: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'parent_id' in 'INSERT INTO'"

In ExceptionConverter.php line 69:
                                                                                               
  An exception occurred while executing a query: SQLSTATE[42S22]: Column not found: 1054 Unkn  
  own column 'parent_id' in 'INSERT INTO'                                                      
                                                                                               

In Exception.php line 24:
                                                                                       
  SQLSTATE[42S22]: Column not found: 1054 Unknown column 'parent_id' in 'INSERT INTO'  
                                                                                       

In Statement.php line 130:
                                                                                       
  SQLSTATE[42S22]: Column not found: 1054 Unknown column 'parent_id' in 'INSERT INTO'  
                                                                                       

doctrine:migrations:execute [--write-sql [WRITE-SQL]] [--dry-run] [--up] [--down] [--query-time] [--configuration CONFIGURATION] [--em EM] [--conn CONN] [--] <versions>...
```


I went passed those 2 errors and continued with the other migration. Then after executing all the migrations, I executed again the 2 migrations above and it worked with no problem, so there is a problem with the ordering of the migration. When we modify the structure of an entity it should be placed at the beginning of the migration process.

The parent_id error is related to the 2 new migrations integrated in your PR so you have to check where this modification should be included not to block other migrations.

Once the migration done I started to test the functionality.

The existing documents before the migration are still present and inside the correct folder so the migration seems fine.
I created a new file and a new folder and it works fine.
I created a file inside the new folder
I attach this last file to 2 other courses and the resource_link was created correctly and the file appear at the root of the document folder in the new courses. So all good.

I wanted to move the file to a folder but the functionality is not working. In the window that opens it indicates that there are no folder. We can see on the image that there is no destination folder available on the window when we can see on the background that there are 2 folders available.

<img width="1275" height="511" alt="Image" src="https://github.com/user-attachments/assets/9f810bfe-106f-4f07-898e-7d43ed3229fb" />

So the document tool seems to work fine, just need to be able to test file move and confirm that the same file in different course can be in different folders.

**Comment by christianbeeznest** [comment]
> Hi [@christianbeeznest](https://github.com/christianbeeznest)
> 
> I tested your PR on testing23 and I have the followinf issues to be checked :
> 
> On testing23 the last migration before updating to your branch "[GH-6372](https://github.com/chamilo/chamilo-lms/issues/6372)-4" was "Version20250725104800". So I had to apply all the migrations since then.
> 
> And I got the following errors :
> 
> ```
> 

It is checked and improved with this commit https://github.com/christianbeeznest/chamilo-lms/commit/2ff4bb17814d34d3516d4b1220022da1cfd880cc

Thanks for confirmation.

**Comment by NicoDucou** [comment]
Hi @christianbeeznest 

The move document functionality is working fine now but the migration is still a problem.

You moved the migracion to create the parent_id field from Version20251201164100 to Version20250922120000 but it is not enough. The entities modifications must be done at the beginning of the migration process because when a migration uses the entity it will no have the correct structure in the database and an error will occur.

I tried to do a complete migration with your branch and I have an error with the parentid at the beginning :

```
root@testing:/var/www/testing21.beeznest.com/www# UPDATE_PATH=/var/www/testing1.beeznest.com/www time php bin/console doctrine:migrations:migrate

 WARNING! You are about to execute a migration in database "testing21" that could result in schema changes and data loss. Are you sure you wish to continue? (yes/no) [yes]:
 > yes

[notice] Migrating up to Chamilo\CoreBundle\Migrations\Schema\V200\Version20251204120000
[warning] Migration Chamilo\CoreBundle\Migrations\Schema\V200\Version20191206150030 was executed but did not result in any SQL statements.
[warning] Migration Chamilo\CoreBundle\Migrations\Schema\V200\Version20200821224230 was executed but did not result in any SQL statements.
[warning] Migration Chamilo\CoreBundle\Migrations\Schema\V200\Version20200821224245 was executed but did not result in any SQL statements.
[warning] Migration Chamilo\CoreBundle\Migrations\Schema\V200\Version20201010224040 was executed but did not result in any SQL statements.
[warning] Migration Chamilo\CoreBundle\Migrations\Schema\V200\Version20201210100011 was executed but did not result in any SQL statements.
MIGRATIONS :: FILE -- Version20201211114900 ...
[error] Migration Chamilo\CoreBundle\Migrations\Schema\V200\Version20201212195011 failed during Execution. Error: "An exception occurred while executing a query: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'parent_id' in 'INSERT INTO'"

In ExceptionConverter.php line 69:
                                                                                                                                      
  An exception occurred while executing a query: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'parent_id' in 'INSERT INTO'  
                                                                                                                                      

In Exception.php line 24:
                                                                                       
  SQLSTATE[42S22]: Column not found: 1054 Unknown column 'parent_id' in 'INSERT INTO'  
                                                                                       

In Statement.php line 130:
                                                                                       
  SQLSTATE[42S22]: Column not found: 1054 Unknown column 'parent_id' in 'INSERT INTO'  
                                                                                       
```

So I just changed the migration Version20250922120000 to Version20200101010000 and now the migration went until the end.


I Accept the PR and I will send the migration reordening.

I assign the issue to you @christianbeeznest for you to know about this migration issue to avoid it next time.
Once you revised my comment you can close the issue.

**Comment by christianbeeznest** [comment]
Thank you Nicolas, indeed, resource link is called from previous migration files. I close this ticket .
