### ISSUE TITLE
[C2] Forum: learner grading give a 500 error

### ISSUE THREAD

**Issue by NicoDucou** [chamilo/chamilo-lms#7039]
When entering the page to grade learner in a thread of a forum it gives a 500 error and in the logs we can see: 

`[Wed Nov 12 15:22:06.697815 2025] [proxy_fcgi:error] [pid 534307] [client 2a01:e0a:e5f:f620:32ac:68e2:86a2:40e1:52652] AH01071: Got error 'PHP message: PHP Fatal error:  Uncaught TypeError: get_thread_users_details(): Argument #1 ($thread_id) must be of type int, string given, called in /var/www/testing24.beeznest.com/www/public/main/forum/viewforum.php on line 207 and defined in /var/www/testing24.beeznest.com/www/public/main/forum/forumfunction.inc.php:1415\nStack trace:\n#0 /var/www/testing24.beeznest.com/www/public/main/forum/viewforum.php(207): get_thread_users_details()\n#1 {main}\n  thrown in /var/www/testing24.beeznest.com/www/public/main/forum/forumfunction.inc.php on line 1415', referer: https://testing24.beeznest.com/main/forum/viewforum.php?cid=17&sid=0&gid=0&gradebook=0&origin=&gid=0&forum=1
`

On Chamilo Master the 12/11/2025

**Comment by christianbeeznest** [comment]
It is checked and fixed with this commit https://github.com/chamilo/chamilo-lms/pull/7049/commits/b27148ae310452cdfefd500095f0b4c0b9f06071

Thanks for confirmation.

**Comment by NicoDucou** [comment]
Hi @christianbeeznest 
When opening the page https://testing24.beeznest.com/main/forum/viewforum.php?forum=1&cid=17&sid=0&gid=0&gradebook=1&origin= then clicking on the line of the thread "Thread for example" on the icon : 
<img width="37" height="46" alt="Image" src="https://github.com/user-attachments/assets/065a94b2-c22c-41b9-b510-dae49512c986" />

It opens the page https://testing24.beeznest.com/main/forum/viewforum.php?cid=17&sid=0&gid=0&gradebook=1&origin=&forum=1&forum=1&action=liststd&content=thread&id=1

And in the logs I have :
`[Mon Nov 17 14:17:10.843622 2025] [proxy_fcgi:error] [pid 648709] [client 2a01:e0a:e5f:f620:3304:126c:c6a7:8b97:50868] AH01071: Got error 'PHP message: An exception occurred while executing a query: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'c_id' in 'WHERE'', referer: https://testing24.beeznest.com/main/forum/viewforum.php?forum=1&cid=17&sid=0&gid=0&gradebook=1&origin=`

So I can not check this issue for the moment.

**Comment by christianbeeznest** [comment]
> Hi [@christianbeeznest](https://github.com/christianbeeznest) When opening the page https://testing24.beeznest.com/main/forum/viewforum.php?forum=1&cid=17&sid=0&gid=0&gradebook=1&origin= then clicking on the line of the thread "Thread for example" on the icon : <img alt="Image" width="37" height="46" src="https://private-user-images.githubusercontent.com/6579268/515185594-065a94b2-c22c-41b9-b510-dae49512c986.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NjM2MjE3MTIsIm5iZiI6MTc2MzYyMTQxMiwicGF0aCI6Ii82NTc5MjY4LzUxNTE4NTU5NC0wNjVhOTRiMi1jMjJjLTQxYjktYjUxMC1kYWU0OTUxMmM5ODYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI1MTEyMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNTExMjBUMDY1MDEyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZmRhOWFhOTYyZDcwOGE5NmE1YWIyNzM5Njg5NmM3NjNjNTVlMDJhZTU5Y2Y1MTJmNjAzOTEzMzlkZGM4MGRjYSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.F-9ct9op8WT_6xztxA8x7tePLbOqmRjTT--X6UnaSAU">
> 
> It opens the page https://testing24.beeznest.com/main/forum/viewforum.php?cid=17&sid=0&gid=0&gradebook=1&origin=&forum=1&forum=1&action=liststd&content=thread&id=1
> 
> And in the logs I have : `[Mon Nov 17 14:17:10.843622 2025] [proxy_fcgi:error] [pid 648709] [client 2a01:e0a:e5f:f620:3304:126c:c6a7:8b97:50868] AH01071: Got error 'PHP message: An exception occurred while executing a query: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'c_id' in 'WHERE'', referer: https://testing24.beeznest.com/main/forum/viewforum.php?forum=1&cid=17&sid=0&gid=0&gradebook=1&origin=`
> 
> So I can not check this issue for the moment.

It is checked with this commit https://github.com/chamilo/chamilo-lms/pull/7084/commits/27f8e8a5c22a2a60bab92c9edd43fdcfa4d9f029

Thanks for confirmation.

**Comment by NicoDucou** [comment]
Hi @christianbeeznest 

With your new commit I can go a bit futher but I still have an error.
I'm getting to this page https://testing24.beeznest.com/main/forum/viewforum.php?cid=17&sid=0&gid=0&gradebook=0&origin=&forum=1&action=liststd&content=thread&id=1&list=all
In the list of users I have "student2 BeezNest (student)" and in the "Grade activity" column I have the icon to give a mark to the student.

<img width="30" height="27" alt="Image" src="https://github.com/user-attachments/assets/e7217da0-0be8-46f4-9230-6254d77559cf" />

When clicking on this icon it opens the page https://testing24.beeznest.com/main/forum/forumqualify.php?cid=17&sid=0&gid=0&gradebook=0&origin=&forum=1&thread=1&user=5&user_id=5&idtextqualify=0

This page does not load correctly and in the error logs we have :
`[Fri Nov 21 10:55:16.829287 2025] [proxy_fcgi:error] [pid 15393] [client 2a01:e0a:e5f:f620:bb5:6927:93e9:9b31:55140] AH01071: Got error 'PHP message: PHP Fatal error:  Uncaught ErrorException: Warning: Undefined array key "user_id" in /var/www/testing24.beeznest.com/www/public/main/forum/forumqualify.php:306\nStack trace:\n#0 {main}\n  thrown in /var/www/testing24.beeznest.com/www/public/main/forum/forumqualify.php on line 306', referer: https://testing24.beeznest.com/main/forum/viewforum.php?cid=17&sid=0&gid=0&gradebook=0&origin=&forum=1&action=liststd&content=thread&id=1&list=all
`

**Comment by christianbeeznest** [comment]
> Hi [@christianbeeznest](https://github.com/christianbeeznest)
> 
> With your new commit I can go a bit futher but I still have an error. I'm getting to this page https://testing24.beeznest.com/main/forum/viewforum.php?cid=17&sid=0&gid=0&gradebook=0&origin=&forum=1&action=liststd&content=thread&id=1&list=all In the list of users I have "student2 BeezNest (student)" and in the "Grade activity" column I have the icon to give a mark to the student.
...
> This page does not load correctly and in the error logs we have : `[Fri Nov 21 10:55:16.829287 2025] [proxy_fcgi:error] [pid 15393] [client 2a01:e0a:e5f:f620:bb5:6927:93e9:9b31:55140] AH01071: Got error 'PHP message: PHP Fatal error: Uncaught ErrorException: Warning: Undefined array key "user_id" in /var/www/testing24.beeznest.com/www/public/main/forum/forumqualify.php:306\nStack trace:\n#0 {main}\n thrown in /var/www/testing24.beeznest.com/www/public/main/forum/forumqualify.php on line 306', referer: https://testing24.beeznest.com/main/forum/viewforum.php?cid=17&sid=0&gid=0&gradebook=0&origin=&forum=1&action=liststd&content=thread&id=1&list=all `

It is checked and improved with this commit https://github.com/chamilo/chamilo-lms/pull/7096/commits/d07c146baa576898f7676d94227590cb072c9deb

Thanks for confirmation.

**Comment by NicoDucou** [comment]
Hi @christianbeeznest 

The error is solved but I'm blocked a bit later.
When I try to asign a mark to the user on https://testing24.beeznest.com/main/forum/forumqualify.php?cid=17&sid=0&gid=0&gradebook=0&origin=&forum=1&thread=1&user=5&user_id=5&idtextqualify=0

I have the field "Score" with an indication of "Max score 0" so if I set a score to the learner it is not accepted unless I put 0.

This Max score correspond to the field c_forum_thread.thread_qualify_max which is set when the thread is added in the gradebook.

To be easier for the user, in the advanced parameters of a thread in C1 we have added a checkbox "Grade this thread" and when you select it, other fields appear to configure the gradebook :

<img width="1025" height="629" alt="Image" src="https://github.com/user-attachments/assets/5087215c-172e-4434-8743-e2644e8c6520" />


This should be added in C2 in the thread edition form https://testing24.beeznest.com/main/forum/editthread.php?cid=17&sid=0&gid=0&gradebook=1&origin=&forum=1&thread=2&id_attach=

**Comment by christianbeeznest** [comment]
> Hi [@christianbeeznest](https://github.com/christianbeeznest)
> 
> The error is solved but I'm blocked a bit later. When I try to asign a mark to the user on https://testing24.beeznest.com/main/forum/forumqualify.php?cid=17&sid=0&gid=0&gradebook=0&origin=&forum=1&thread=1&user=5&user_id=5&idtextqualify=0
> 
> I have the field "Score" with an indication of "Max score 0" so if I set a score to the learner it is not accepted unless I put 0.
> 
> This Max score correspond to the field c_forum_thread.thread_qualify_max which is set when the thread is added in the gradebook.
> 
> To be easier for the user, in the advanced parameters of a thread in C1 we have added a checkbox "Grade this thread" and when you select it, other fields appear to configure the gradebook :
> 

It is checked with this commit https://github.com/chamilo/chamilo-lms/pull/7100/commits/29e21dab4b0fa1142a1be4217ae08a04a76a5ee6

Thanks for confirmation.

**Comment by NicoDucou** [comment]
All good now.
Closing this issue
